%YAML 1.1
---
# CPAC Pipeline Configuration YAML file
# Version 1.8.2
#
# http://fcp-indi.github.io for more info.
#
# Pipeline config "Default", version GUI-0
# Fri Dec 10 2021 15:50:24 GMT-0500 (Eastern Standard Time)
#
# Tip: This file can be edited manually with a text editor for quick modifications.

FROM: default

pipeline_setup:
  system_config:
    raise_insufficient: Off
  Debugging:
    verbose: true

